version: "3"
services:
  mongodb:
    image: mongo:4.2.3
    container_name: "mongodb"
    ports:
    - 27017:27017
  app:
    image: alexoshiro/register-api
    ports:
    - 8080:8080
    links:
    - mongodb 