version: "3"
services:
  registerapi:
    image: alexoshiro/register-api:latest
    ports:
    - 8080:8080
    environment:
    - MONGO_URI=CHANGE_TO_YOUR_MONGO_URI_CONNECTION_STRING
    links:
    - mongodb
  registerui:
    image: alexoshiro/register-ui:latest
    ports:
    - 80:80
    links:
    - registerapi